# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: install protoc
    init: |
      brew install protobuf
      protoc --version
  - name: install go protoc plugins
    init: |
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
  - name: Install go dependencies
    init: |
      go install github.com/go-delve/delve/cmd/dlv@latest
      go install honnef.co/go/tools/cmd/staticcheck@latest

vscode:
  extensions:
    - golang.go
    - zxh404.vscode-proto3