# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: install protoc
    init: |
      protoc --version
  - name: install go protoc plugins
    init: |
      go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      go install github.com/gogo/protobuf/protoc-gen-gofast
      go install github.com/gogo/protobuf/protoc-gen-gogoslick
      go install github.com/AsynkronIT/protoactor-go/protobuf/protoc-gen-gograinv2@dev
  - name: Install go dependencies
    init: |
      go install github.com/go-delve/delve/cmd/dlv@latest
      go install honnef.co/go/tools/cmd/staticcheck@latest

vscode:
  extensions:
    - golang.go
    - zxh404.vscode-proto3

ports:
  - port: 5050
    visibility: public
    onOpen: ignore
  - port: 5432
    visibility: public
    onOpen: ignore
  - port: 8080
    visibility: public
    onOpen: ignore