version: '3.8'
services:
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@somewhere.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"